require("aryanz.plugins-setup")
require("aryanz.core.options")
require("aryanz.core.keymaps")
require("aryanz.core.colorscheme")
require("aryanz.plugins.comment")
require("aryanz.plugins.nvim-tree")
require("aryanz.plugins.lualine")
require("aryanz.plugins.telescope")
require("aryanz.plugins.nvim-cmp")
require("aryanz.plugins.lsp.mason")
require("aryanz.plugins.lsp.lspsaga")
require("aryanz.plugins.lsp.lspconfig")
-- require("aryanz.plugins.lsp.null-ls")
-- require("aryanz.plugins.autopairs")
-- require("aryanz.plugins.treesitter")
-- require("aryanz.plugins.gitsigns")

